### ISSUE TITLE
 400 Client Error: Bad Request

### ISSUE THREAD

**Issue by aspergerish** [coursera-dl/coursera#308]
Hi I am currently unable to use this program due to this error message: " 400 Client Error: Bad Request". What gives?

**Comment by rbrito** [comment]
Hi, @aspergerish.

It is hard to know what is happening. Please, provide the output of the program when you use the `--debug` option, so that we can better understand what may be happening.

In general, please see the instructions at https://github.com/coursera-dl/coursera#troubleshooting to check for potential problems.

Hope this helps,

Rogério.

**Comment by aspergerish** [comment]
Hi, @rbrito 

Thanks for the reply, I think I remember using --debug, but did not see anything useful. It is currently working, and I now believe that the problem happened due to Coursera's outage that day.

Thanks!
