### ISSUE TITLE
The filename or extension is too long

### ISSUE THREAD

**Issue by Wandalen** [coursera-dl/coursera#342]
Tried to download course chemhealth-002. OS: Windows.
Got:
Traceback (most recent call last):
  File "D:\dev\python2\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()
  File "D:\dev\python2\lib\site-packages\courseradownloader\courseradownloader.py", line 654, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse,gzip_courses = args.gzip_courses)
  File "D:\dev\python2\lib\site-packages\courseradownloader\courseradownloader.py", line 482, in download_course
    os.makedirs(clsdir)
  File "D:\dev\python2\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 206] The filename or extension is too long: 'H:\\Education\\Biochemistry\\Chemicals and Health\\chemhealth-002\\01 - Module 1 Chemicals in our environment What is a chemical and how are we exposed\\04 - Lecture 1C Chemicals in Our Environment What Is a Chemical and How Are We Exposed (2125) - Burke'

**Comment by rbrito** [comment]
Hi, @Wandalen.

You seem to be using a different project also called `coursera-dl` (yes, we know it is confusing).

That being said, our project is also affected by this exact same problem (see #239 and #217), mainly because computers are too limited for our human needs. Anyway, I hope to address the problem in a not-so-clean way in the near future (I already have a kludgy idea).

You are, though, more than welcome to try our script and see if it suits you better. I am, therefore, closing this bug.


Regards,

Rogério Brito.

**Comment by Wandalen** [comment]
Oh, I see, Thanks.
