### ISSUE TITLE
feature request: all but ... file formats

### ISSUE THREAD

**Issue by rivokl** [coursera-dl/coursera#361]
Is it possible to specify all but mp4, say ,as file formats? As in -f 'all -mp4'??

**Comment by rbrito** [comment]
Hi.

On May 20 2015, Kely wrote:
> Is it possible to specify all but mp4, say ,as file formats? As in -f 'all -mp4'??

Not yet, but something along these lines would be relatively easy to
implement.

I think that I can leave this as a bug open to newcomers to the project that
would like to start contributing some code and getting involved.


Thanks for the suggestion,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by madmax2** [comment]
Can you support automatically download of PDF handouts, course materials?

Coursera-dl can download everything not just videos..

**Comment by asiviero** [comment]
I will give this a try.

@rbrito what would be a good parameter for this? -f ? -i? --ignore-file-format?

Also, it would be interesting to ignore multiple file formats too, splitting them with a comma, like -f "mp4,srt"

**Comment by rbrito** [comment]
Hi, Andre.

On Jun 02 2015, Andre Siviero wrote:
> I will give this a try.

Excellent.

> @rbrito what would be a good parameter for this? -f ? -i?
> --ignore-file-format?

Let's try to save one-letter options to thoses that are most frequently
used.  In fact, I have been thinking about deprecating some options and then
removing them so that we have a better command line interface.

That being said, yes, I think that what you propose is a sensible choice of
name for the option. In fact, to be consistent with the already existing
option named --formats, I suppose that --ignore-formats would be better.

> Also, it would be interesting to ignore multiple file formats too,
> splitting them with a comma, like -f "mp4,srt"

I agree. There are some courses that started to upload lower definition
videos that are actually *bigger* (in size) than the regular videos.
Luckily, they have the extension mov.

Furthermore, I generally have little use for the txt files (they generally
have the same contents as the srt files), but care should be taken when
excluding those files, as instructors may put extra text files attached to
some lectures.

It would be nice if you put a comment along the lines of my comment above in
the documentation (and I think that we should put, somehow, the options of
the program in the documentation---perhaps in an automated way, like
youtube-dl does).

OK, this was a long reply to some simple questions, but I couldn't avoid
commenting on the excess of one-letter options and my dislike.


Thanks,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by asiviero** [comment]
Alright, I'll submit a PR when I'm done.

Thank you
